### ISSUE TITLE
I can help

### ISSUE THREAD

**Issue by eriklenaerts** [kerkenit/nl.marcovantklooster.pioneer#2]
hey, I have a VSX 1021 and couldn't get it to work. Perhaps I can help out. Note that my dev skills are a bit rusty and I'm new to Homey as well. Any idea how I can assist? Perhaps try a few things out?

**Comment by kerkenit** [comment]
If I have the control of the device in my own house, I can maybe reverse engineering to make it work. But I guess that is impossible.
Right now I have no idea how I can help you.

**Comment by eriklenaerts** [comment]
hey, I tried again today and it works. Didn't change a thing... weird, but happy :)

**Comment by kerkenit** [comment]
Thats awesome. Happy listening
