### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by dENNtoet** [kerkenit/nl.marcovantklooster.pioneer#3]
Hi!

Thanks for the app so far, I have a VSX-521 which is working perfectly for the options I am using. 
I was just wondering since Homey just released the new 1.2 update with the Media now available if it would be possible to set the receiver as active speaker within Homey by using Bluetooth for example. 

Is this a feature what you guys are planning to implement in the near future because that would be freaking awesome! 

Hope to hear from you soon!

Kind regards,
Dennis

**Comment by dENNtoet** [comment]
Apparently you need an extra module for Bluetooth which is about 100 euros.. I'll look at some other alternatives.

**Comment by kerkenit** [comment]
This can be done by DNLA. I'm gonna develop it a soon as Athom has the API done.

**Comment by kerkenit** [comment]
Note to myself http://192.168.1.7:8080/description.xml

**Comment by Pauweltje** [comment]
I guess this project is dead as it is?

**Comment by kerkenit** [comment]
Sort of. Yesterday I send a update to the app store. But it still remains "for sale" See forum
