### ISSUE TITLE
VSX-521 Power On doesn't work

### ISSUE THREAD

**Issue by dENNtoet** [kerkenit/nl.marcovantklooster.pioneer#4]
Hi, 

I am using Homey update 1.2 RC9 and I am an owner of the Pioneer VSX-521. Volume up/down and turning off works like a charm. But turning the device ON isn't working.. 

Any ideas?

Kind regards,
Dennis

**Comment by uNiiek** [comment]
Hi,

i've got the same problem: Turning on mij VSX-921 isn't working.
The other commands works.

I hope that you can find the problem.

Kind regards,
Niek

**Comment by dENNtoet** [comment]
Hi Niek,

**Comment by uNiiek** [comment]
Hi DENNtoet,

I just figured out how to power on de VSX-921 remotely:

For me this did the trick:

1. Turn on the tv and set it on the right HDMI source of the receiver (make sure youre Pioneer is connected with the internet)
2. Download and install de iControlAV5 app on your mobile
3. Open the app
4. Go to the "cursor" page 
5. Press "Audio parameter" (Now you get the advanced MCACC menu on your TV)
6. Select "System settings" (or something. I translate is from Dutch)
7. Select "Network settings"
8. Select "Network standby"en switch is to "ON"

Hope this will als work for you!

Kind regards,
Niek

**Comment by dENNtoet** [comment]
Yep works!
